server:
  port: 9191
  connection-timeout: 300000
spring :
  application :
    name : api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/dept/**
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**
eureka:
  client:
    register-with-eureka : true
    fetch-registry: true
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
  instance:
    hostname: localhost